when:
  - event: push
    branch: main
  - event: tag
    ref: refs/tags/v*

variables:
  - &registry    ghcr.io
  - &image       ghcr.io/manawenuz/enkodu

steps:
  - name: build-queue-image-push
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    labels:
      platform: linux/amd64
    settings:
      registry: *registry
      repo: *image
      tags:
        - "${CI_COMMIT_SHA}"
        - main
      username:
        from_secret: ghcr_user
      password:
        from_secret: ghcr_token
      platforms: linux/amd64
      dockerfile: queue/Dockerfile
      context: queue/
    when:
      - event: push
        branch: main

  - name: build-queue-image-release
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    labels:
      platform: linux/amd64
    settings:
      registry: *registry
      repo: *image
      tags:
        - "${CI_COMMIT_TAG##v}"
        - latest
      username:
        from_secret: ghcr_user
      password:
        from_secret: ghcr_token
      platforms: linux/amd64
      dockerfile: queue/Dockerfile
      context: queue/
    when:
      - event: tag
        ref: refs/tags/v*
